project:
  type: website
  output-dir: docs

website:
  title: "Maya Garcia's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me!
      - href: Test.qmd
        text: STAT 244-SC

format:
  html:
    css: styles.css
    toc: true
    dark: darkly
    theme: pulse
    linkcolor: "#FF69B4"
    #backgroundcolor: "#FFC0CB"

editor: visual

